name: 'Release Modpack Action From Release'
description: 'This automatically downloads the newest release and description and uploads it to vendors!'

inputs:
  loader:
    description: 'Current modpack loader'
    required: true
  game-version:
    description: 'Current modpack game version'
    required: true
  upload-modrinth:
    description: 'Set to true to upload the modpack to Modrinth'
    required: true
  upload-curse:
    description: 'Set to true to upload the modpack to CurseForge'
    required: true
  MODRINTH_TOKEN:
    required: false
    description: 'Token used for uploading modpack to Modrinth'
  MODRINTH_ID:
    required: false
    description: 'ID used for uploading modpack to Modrinth'
  CURSEFORGE_TOKEN:
    required: false
    description: 'Token used for uploading modpack to CurseForge'
  CURSEFORGE_ID:
    required: false
    description: 'ID used for uploading modpack to CurseForge'
  modpack:
    description: 'Path to the modpack directory'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Check Out Git Repository
      uses: actions/checkout@v3

    - name: Download the pack files
      uses: robinraju/release-downloader@v1.8
      id: download-files
      with:
        fileName: '*'
        latest: true
        tarBall: false
        zipBall: false
      working-directory: ${{ inputs.modpack }}

    - name: Get latest release description
      id: latest-release
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        repository: ${{ github.repository }}
        token: ${{ github.token }}
      working-directory: ${{ inputs.modpack }}

    - name: Pipe latest release description to file
      run: echo "${{ steps.latest-release.outputs.description }}" > CHANGELOG.release.md
      shell: bash
      working-directory: ${{ inputs.modpack }}

    - name: Print status
      run: |
        echo "::notice ::⚙ Assets for ${{ inputs.modpack }} from the latest release ${{ steps.latest-release.outputs.release }} downloaded successfully!"
        echo "::notice ::⚙ Latest release for ${{ inputs.modpack }} ${{ steps.latest-release.outputs.release }} description piped into a file successfully!"
      shell: bash

    - name: Publish to Modrinth
      env:
        LOADER: ${{ inputs.loader }}
        GAME_VERSION: ${{ inputs.game-version }}
      if: inputs.upload-modrinth == 'true'
      uses: Kir-Antipov/mc-publish@v3.2
      with:
        modrinth-id: ${{ env.MODRINTH_ID }}
        modrinth-token: ${{ env.MODRINTH_TOKEN }}
        loaders: ${{ env.LOADER }}
        game-versions: ${{ env.GAME_VERSION }}
        changelog-file: CHANGELOG.release.*
        files: '*.mrpack'
      working-directory: ${{ inputs.modpack }}

    - name: Publish to CurseForge
      env:
        LOADER: ${{ inputs.loader }}
        GAME_VERSION: ${{ inputs.game-version }}
      if: inputs.upload-curse == 'true'
      uses: Kir-Antipov/mc-publish@v3.2
      with:
        curseforge-id: ${{ env.CURSEFORGE_ID }}
        curseforge-token: ${{ env.CURSEFORGE_TOKEN }}
        loaders: ${{ env.LOADER
