on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: 'The release tag to bump the releases to'
        required: false
        default: 'v1.0.0'
        type: string
      modpack:
        description: 'Path to the modpack directory'
        required: false
        default: 'main'
        type: string
  workflow_call:
    inputs:
      release-tag:
        description: 'The release tag to bump the releases to'
        required: true
        type: string
      modpack:
        description: 'Path to the modpack directory'
        required: false
        default: 'main'
        type: string


jobs:
  set-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Git Repository
        uses: actions/checkout@v3

      - name: Set the new version
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_options: '--allow-empty'
          commit_message: |
            chore(${{ inputs.modpack }}): release ${{ inputs.release-tag }}
            Release-As: ${{ inputs.release-tag }}}