name: Set version | Manual Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Specify the initial release version (including the 'release' prefix, e.g., v1.0.0?"
        required: true
        type: string
jobs:
  set-version:
    name: Set Version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check Out Git Repository
        uses: actions/checkout@v3

      - name: Add the version
        run: 'git commit --allow-empty -m "chore: release ${{ inputs.version }}" -m "Release-As: ${{ inputs.version }}"'
    
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
