name: Setup repository

on:
  create

jobs:
  initial-version:

    permissions:
      contents: write

    if: github.event.ref == github.event.master_branch
    uses: ./.github/workflows/bump-version-release.yml
    with:
      release-tag: 0.1.0